name: HCraftVanillaFirstJoinChest
main: me.dakto101.HCraftVanillaFirstJoinChest
version: 1.1
api-version: 1.13
depend: 
softdepend: []
commands:
    firstjoinchest:
        description: aa.
        usage: /<command>